import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from './header'
import Intro from './intro'
import Projects from './projects'
import Education from './education'
import Footer from './footer'
import MyApps from './myApps'
import YoutubeEmbed from './components/youtubeEmbed'

export default function Home() {
  return (
    <>
      <Head>
        <title>Sanij Shrestha</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"></link>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Header />
        <Intro />
        
        {/* <Projects /> */}
        <MyApps />
        {/* <Education /> */}
        <Footer />
      </main>
    </>
  )
}
